services:
  - type: web
    name: martapp-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    runtime:
      pythonVersion: 3.11.9
    rootDir: api
